### ISSUE TITLE
[Suggestion] Be able to limit how many times a player or team can change classes in-game.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#120]
I was wondering if it was possible to limit how many times a specific individual could change classes in-game or how many times a team can change classes overall. This would allow for more tactical thinking in gameplay balancing. Such as if a team needs more defenders or if a player doesn't want to be a light class anymore.

Examples being everyone being able to change their class once in-game or each team only allowing 3 changes total the entire game duration.

**Comment by slipcor** [comment]
https://github.com/slipcor/pvparena_modules/search?utf8=%E2%9C%93&q=parseClassChange

should be done :) right, @mibby ?

**Comment by mibby** [comment]
This is not working as intended. I am able to change classes unlimited times. Tested both team and player limits set.

```
    maxTeamSwitches:
      Red: 3
      Blue: 3
    maxPlayerSwitches: 1
```

**Comment by slipcor** [comment]
Oh I did a messup :P should be fixed! v1.3.2.120 - [BetterClasses] address github issue #120

**Comment by mibby** [comment]
Still not functioning as intended. No limit in place whatsoever when switching classes in-game, both with a team and player limit set.

**Comment by slipcor** [comment]
v1.3.2.130 - [BetterClasses] enhance debug for github issue #120

**Comment by mibby** [comment]
Here's the debug.
http://paste.ubuntu.com/17080349/

Still not working as intended with limits set. Tested with both team and player limit set to the same thing.
```
    maxTeamSwitches:
      Red: 3
      Blue: 3
    maxPlayerSwitches: 3
```

**Comment by slipcor** [comment]
I am sorry to say that I only could add more debug. The debug you did returned no further helpful output :/

v1.3.3.156 - [BetterClasses] - address github issue #120 by adding more debug

**Comment by mibby** [comment]
@slipcor Debug.

CTF
http://paste.ubuntu.com/18479746/

Player 1 switched classes in the lounge both via /pa -ac and the class signs. 
Player 2 switched classes in-game in the battlefield via /pa -ac. 
Player 1 should not be limited as it was switching classes in the lounge.
Player 2 should have been limited, per the maxteamswitches/maxplayerswitches setting.

No player was limited.

**Comment by slipcor** [comment]
Aww dude xD you switched to the same class. As that does not change anything I skipped the class change parsing there. Meh. well I guess it should be checked, and parsed. Next version will always check :P
