### ISSUE TITLE
Team name is not colored on scoreboard in domination / king of the hill goals.

### ISSUE THREAD

**Issue by mibby** [slipcor/pvparena#201]
Something broke. Team names are not colored in domination or KOTH goals with the scoreboard module, while they are in CTF.

**Comment by slipcor** [comment]
mhhh can you do a debug of both? :/ sorry but I checked the code and I see nothing that the goal SHOULD or COULD do about this :/

**Comment by mibby** [comment]
Sure thing. It use to work in Domination per the image taken in this ticket. 
https://github.com/slipcor/pvparena/issues/111 So no idea what broke it since then. :P

Debug of KOTH (where it doesn't work).
http://paste.ubuntu.com/16715897/

Debug of CTF (where it works).
http://paste.ubuntu.com/16715874/

**Comment by slipcor** [comment]
Can you please try this version I am pushing to modules right now?

v1.3.2.120 - [ScoreBoards] add debug and explicit Exceptions - use with caution :P

It might actually spam/show some exceptions (while/before trying to set the color)

**Comment by mibby** [comment]
http://paste.ubuntu.com/16857939/
http://paste.ubuntu.com/16857947/
http://paste.ubuntu.com/16857953/

**Comment by slipcor** [comment]
Because of the things you have at spawn... I forgot what it was but ever since you added those this showed up :)

**Comment by slipcor** [comment]
ScoreBoard NPE should be fixed in "v1.3.2.133 - [ChestFiller] add github issue #200, a configurable chest to set items"

The rest should be fixed in main plugin AND moduels (!!)

v1.3.2.134 - [FlySpecate,RealSpecate,SinglePlayerSupport,Spectate] address github issue #201 - properly call PAJoinEvent, this never was implemented correctly. Sorry!

**Comment by mibby** [comment]
Still broken. Tested with you.

**Comment by mibby** [comment]
Still broken as of PA 1.3.2.141, Beacons 1.3.2.99, ColorTeams 1.3.2.136, and Scoreboards 1.3.2.137. Team names are white on the scoreboard in KOTH/DOM.

**Comment by slipcor** [comment]
@mibby debug? :D

**Comment by mibby** [comment]
@slipcor Debug.

KOTH
http://paste.ubuntu.com/18479071/

General
http://paste.ubuntu.com/18479099/

I think for the most part, the debugs are the same as the one posted above.

PA 1.3.3.158
ColorTeams 1.3.2.136
Scoreboards 1.3.2.137
Beacons 1.3.2.99

**Comment by slipcor** [comment]
@mibby I must ask of you to run this again with the latest scoreboards, (more debug) and please with both arenas (CTF working, right?) I do not understand, I see no difference in the debugs of the things you linked so far :/

**Comment by mibby** [comment]
It seems the team names on the scoreboard are also not colored in my paintball arena when testing with latest scoreboards module as well. :( CTF is still fine.

Debug of paintball.
http://paste.ubuntu.com/22081798/

**Comment by slipcor** [comment]
the thing is that I do not think it is something with the scoreboard mechanic, but something about the general behavior of how the arena works, maybe in which orders modules are hooked, maybe IF some modules are called at all, and I strongly believe it has to do with the game mode.

I will try to debug this on my own then. I tried reading through the code and I have not found any differences, but without a doubt there HAS to be a difference, otherwise the result would be the same :P

**Comment by slipcor** [comment]
@mibby can you please send me your CTF config? For me it is consistent in the sense that it NEVER is colored.... I would be interested in knowing how you made it work at all -.-

**Comment by slipcor** [comment]
forgot to link this ticket in v1.3.3.186 - implement ColorTeams and ScoreBoards modules into core - addresses github issue #212

has to be fixed :)

**Comment by mibby** [comment]
Finally confirmed fixed! :D KOTH team names are colored again..
